### ISSUE TITLE
documentSelectors with pattern for the same language

### ISSUE THREAD

**Issue by malys** [rioj7/vscode-complete-from-file#1]
Hi @rioj7 ,
Thank you for this plugin. It's quick solution to implement autocompletion.
I have a question for you.

I want to load different "files" depending  a pattern of edited files to load huge autocompletion list in memory unnecessary

```json
"complete-from-file.documents": {
    "cloud completions": {
      "documentSelectors": [
        { "language": "plantuml", "pattern": "**/*cloud*.puml" }
      ],
      "files": [
        "${workspaceFolder}${pathSeparator}plantuml-C4-complete.txt",
...
      ]
    },
    "archi completions": {
      "documentSelectors": [
        { "language": "plantuml", "pattern": "**/*archi*.puml" }
      ],
      "files": [
        "${workspaceFolder}${pathSeparator}plantuml-logo-complete.txt",
....
      ]
    }
  }
```
Like you see, depending on a pattern of filename, I want to load different autompletion files.
I have tried but it's not working. Only "cloud completions" works like expected.

It could be interesting to extend this idea using dynamic parameters (like regex match group)
```json
    "cloud completions": {
      "documentSelectors": [
        { "language": "plantuml", "pattern": "**/test$1.puml" }
      ],
      "files": [
        "${workspaceFolder}${pathSeparator}plantuml-common-complete.txt",
        "${workspaceFolder}${pathSeparator}plantuml-$1-complete.txt",
...
      ]
    }
```

Could you give me your feedback to achieve my goal?

**Comment by rioj7** [comment]
@malys to be sure to know what you want and what you see.

If you have file `file-cloud-xyz.puml` open in an editor you see completions from file `plantuml-C4-complete.txt`

If you have file `file-archi-abc.puml` open in an editor you do **not** see completions from file `plantuml-logo-complete.txt`
Do you get completions from `plantuml-C4-complete.txt`?

----

`"**/test$1.puml"` is not a valid glob pattern

We have to introduce another property that can be transformed to a `pattern` property.

```json
"documentSelectors": [
        { "language": "plantuml", "pattern-ext": "**/test(*).puml" }
      ]
```

you want to capture the `(*)` part of the filename, for `testXYZ.puml` you like to load completion definitions from
`plantuml-XYZ-complete.txt`

**Comment by rioj7** [comment]
@malys Looking at the source code the problem is that I do not test for the `pattern` when loading the completions, if the languageID matches that one is taken, if you change the editor to one with the same languageID but a different `pattern` match it uses the completions already loaded.

I will change that.

**Comment by malys** [comment]
I described 2 ways:
- static way with glob pattern
- dynamic way with capture

I think that you understand my idea.


> @malys Looking at the source code the problem is that I do not test for the `pattern` when loading the completions, if the languageID matches that one is taken, if you change the editor to one with the same languageID but a different `pattern` match it uses the completions already loaded.
> 
> I will change that.

I think that it's the origin of problem (2 patterns for the same language).
In my case, only for the first declaration , autocompletion works fine. The second one was ignore.

Could you inform me to test this new feature?

**Comment by rioj7** [comment]
@malys you can try v0.2.0. It was quite a large change, view the commit.

The dynamic way is moved over to another issue.

**Comment by malys** [comment]
@rioj7 thanks for this feature. it's working well.
